### ISSUE TITLE
Add code linter

### ISSUE THREAD

**Issue by hop-along-polly** [hop-along-polly/always-on#5]
We should strive for clean and consistent code. Black is a really popular linter that we could use for this. Whatever we chose I would like to have the option of customizing the settings just in case a line-length of 80 doesn't work.

**Acceptance Criteria**
 - [x] Linter has a makefile target
 - [x] Linter runs as a Github Action when a PR is opened and updated.
 - [x] Linter does NOT run when commits are pushed to a branch that is associated with a Draft PR or is NOT associated with a PR at all
 - [x] ~~The PR should be blocked until linting is successful.~~

**Comment by hop-along-polly** [comment]
@chrishalbert Would be great having your experience w/ Github Actions to get this setup. If you need addtl permissions for the repo settings let me know and I'll fix that for you.

**Comment by chrishalbert** [comment]
Sounds good, will get started on this!

**Comment by chrishalbert** [comment]
It doesn't look like we can block PRs with a free account so I just scrapped that from the requirements. ([Github Rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#require-status-checks-to-pass-before-merging))

**Comment by chrishalbert** [comment]
Completed in the above PR
